print('Please enter the following information:')
print()
first_name = input('First name: ')
last_name = input('Last name: ')
hair_color = input('Hair color: ')
eyes_color = input('Eyes color: ')
email = input('Email address: ')
phone_num = input('Phone number: ')
job_tittle = input('Job title: ')
month = input('Month you started: ')
training = input('Advanced training? (Yes/No): ')
id_number = input('ID Number: ')

print('The ID Card is:')
print('----------------------------------------')
print(last_name.upper() +', ' + first_name)
print(job_tittle.capitalize())
print(f'ID: {id_number}')
print()
print(email.lower())
print(phone_num)
print()
print(f"{'Hair: ' + hair_color:<25} Eyes: {eyes_color})")
print(f"{'Month: ' + month:<25} Training: {training})")
print('----------------------------------------')